### ISSUE TITLE
Shutting down

### ISSUE THREAD

**Issue by luvarado** [FontaineDenton/FullyNoded#1] opened 2019-03-23 02:38 UTC
I enter all the node information and app shuts off.

**Comment by niallyoung** [comment] 2019-03-23 03:12
Same here - have tried RPC and ssh, both fail to connect and the App gets stuck stuck in a crash loop every time you open it. Need to delete and reinstall, then same issue.

**Comment by FontaineDenton** [comment] 2019-03-23 08:59
I have made some improvements to the code and it should be released in the next day or so. Please update the app when its released and try again. In the meantime if you can give me more info that'd be helpful:

Which ios version are you running? 

Have you configured your ssh config file to allow password log in?

If using rpc have you put "allowip=<yourip>" into your bitcoin.conf file?

**Comment by niallyoung** [comment] 2019-03-25 23:01
Cheers @FontaineDenton , IOS 12.1.4 followed the setup instructions explicitly, no firewall etc. and I confirmed RPC and SSH connectivity beforehand. Looking forward to the next version hitting the App Store, will check out the source and contribute this week hopefully.

**Comment by FontaineDenton** [comment] 2019-03-27 23:39
@niallyoung the update is live. Could you please try it? If you were trying to use a custom port for SSH then that would have been an issue on the original version, new version supports custom ports.

Is Bitcoin Core running on a personal computer or server?

The least amount of things can go wrong with SSH.

If using RPC to connect you need to ensure your ports are open and you are using the correct IP address.

I have used it extensively with SSH password log in on custom port and not had any issues. Ensure you have edited your `/etc/ssh/sshd_config` and uncommented/added `PasswordAuthentication yes` and then `sudo service sshd restart`.

Let me know how it goes.

**Comment by FontaineDenton** [comment] 2019-03-27 23:41
@luvarado  which device are you using? Are you still having an issue with the updated version?

**Comment by niallyoung** [comment] 2019-03-28 09:24
Upgraded Fully Noded, latest IOS that just came out - enter IP address and Port and instant crash. After that point it crashes as soon as it unlocks, every time.

Deleted and reinstalled, started RPC setup again - enter all details, port 8332 and get the new Error screen. Click SSH and I get a spinning progress wheel - and it gets stuck there permanently.

bitcoinf.conf

rpcuser=xxx
rpcpassword=xxx
rpcallowip=x.x.x.x/24
server=1
rest=1
daemon=1

**Comment by FontaineDenton** [comment] 2019-04-01 18:29
@niallyoung Nial which device are you using? Did you update from app store or a side load? Please can you post any screen grabs of errors you get.

There is a known bug that will cause the current version on app store to crash if you have face ID and attempt to log in via biometrics. Other then that I am stumped, have thoroughly tested on all simulator devices running latest ios version...

Reallly appreciate your patience and feedback.

If you tap “Try SSH” then it will always try to connect via SSH, ive changed this for next update which allocates the SSH option to settings so user has control.

**Comment by FontaineDenton** [comment] 2019-04-01 18:45
I have not upgraded to xcode 10, this may be the issue...

**Comment by FontaineDenton** [comment] 2019-04-01 20:00
@niallyoung 

_Deleted and reinstalled, started RPC setup again - enter all details, port 8332 and get the new Error screen. Click SSH and I get a spinning progress wheel - and it gets stuck there permanently._

Is your node public? Does it have incoming connections? Unless you explicitly edit your SSH config file to allow password log in it SSH will not work.

If you specify an IP in rpcallowip=x.x.x.x/24 then your iPhone must be using that IP in order to log in via RPC. 

Also you are specifying port 24 so you'd need to try and connect via port 24 if using RPC, not 8332. Have you tried that?

**Comment by niallyoung** [comment] 2019-04-02 00:20
Yep node is public, has incoming connections - has worked for years. sshd config allows password - I've tested both RPC and SSH connectivity prior to using the App. I'm not side-loading but using the App Store build, was just looking at the source to try and replicate and provide a pull request.

rpcallowip "/24" is a netmask, not a port.

iPhone8, no FaceID but I have used both FN Password and TouchID - once logged in fine I consistently get the Error screen when RPC connections fails, and then when SSH attempts to connect just a progress spinner forever.

**Comment by niallyoung** [comment] 2019-04-02 00:30
UX isn't great - once RPC credentials are saved, if I want to try RPC again I have to re-enter all of them again. Suggest you split Renew into two separate workflows - renew credentials, or try again. Even better would be a separate screen to enter/update credentials separately to trying a connection.

There's no prompt to enter SSH password, so I suspect you're assuming the RPC and SSH passwords are the same. RPC never works for me, but I've set SSH password to same as RPC and tried again - no change, neither RPC nor SSH are ever successful. No firewall, connectivity and passwords confirmed as working, it just doesn't work through FullyNoded.

Have you got physical iPhone devices to test this on?

**Comment by FontaineDenton** [comment] 2019-04-02 11:20
Thanks for the info, yes I have tested thouroughly on physical devices for both RPC and SSH. The app is beta, I am updating and improving all the time. That is a correct assumption about the password for SSH and RPC being the same. The port will be different though. Please just keep updating it in app store. Not sure why its not working for you. Sounds like all the boxes are ticked. Am a bit confused as you say it crashes  everytime you add a port? I guess that was a one off crash? Appreciate the feedback.

**Comment by niallyoung** [comment] 2019-04-02 22:43
"The port will be different though." - are you saying I need to enter 22 as the RPC Port when entering RPC credentials?

The previous version of the App crashed instantly, the latest version doesn't crash it times out.

**Comment by FontaineDenton** [comment] 2019-04-13 23:56
going to close this as the app does not seem to be shutting down with the new update

**Closed by FontaineDenton** 2019-04-13 23:56 UTC

**Comment by johnsonsan** [comment] 2019-10-29 17:12
When coming tk this site 
The dates are so far back, unsure if cerrent message is for me or not. Other than you all are great.
